name: Deploy to Heroku Production

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "obscure-crag-87544-prod" #Must be unique in Heroku
          heroku_email: "jakDev003@gmail.com"
          usedocker: true
